name: _Backup (reusable)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout do código
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configurar SSH
        uses: ./.github/actions/setup-ssh
        with:
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Backup do banco de dados
        env:
          SSH_TARGET: ${{ vars.SSH_TARGET }}
          BACKUP_DB_SCRIPT_PATH: ${{ vars.BACKUP_DB_SCRIPT_PATH }}
        run: |
          # shellcheck disable=SC2029
          ssh "$SSH_TARGET" 'bash -euo pipefail -s' "$BACKUP_DB_SCRIPT_PATH" << 'EOF'
            script_path="$1"
            /bin/bash "$script_path"
          EOF

      - name: Executar scripts de backup na VPS
        env:
          SSH_TARGET: ${{ vars.SSH_TARGET }}
          BACKUP_ENVS_SCRIPT_PATH: ${{ vars.BACKUP_ENVS_SCRIPT_PATH }}
          BACKUP_PASSWORD: ${{ secrets.BACKUP_PASSWORD }}
        run: |
          # shellcheck disable=SC2029
          ssh "$SSH_TARGET" \
            /bin/bash "$BACKUP_ENVS_SCRIPT_PATH" "$BACKUP_PASSWORD"
